app:
  host: "0.0.0.0"
  port: "8081"
  basepath: "/api/*"
  id: "19377379"
  version: "v1"
  name: "dataplatfrom-mule-workday-hcm-s"
  
jsonLogger:
  applicationName: "mule-cloudhub-template"
  applicationVersion: "v1"
  
workday:
  password: "Movement1!"
  hostname: "wd2-impl-services1.workday.com"
  tenant: "movement4"
  username: "ISU_MORE"